name: vietmap_flutter_gl
description: A Flutter map plugin for integrating Vietmap sdk inside a Flutter application, support for show a vector and raster map in Flutter. Supported on Android, iOS platforms .
version: 1.1.7
homepage: https://github.com/vietmap-company
repository: https://github.com/vietmap-company/flutter-map-sdk
issue_tracker: https://github.com/vietmap-company/flutter-map-sdk/issues

dependencies:
  flutter:
    sdk: flutter
  vietmap_gl_platform_interface: ^0.0.6 


flutter:
  plugin:
    platforms:
      android:
        package: vn.vietmap.vietmapgl
        pluginClass: VietmapGLPlugin
      ios:
        pluginClass: MapboxMapsPlugin

environment:
  sdk: '>=2.12.0 <3.0.0'
  flutter: ">=2.0.0"
